#Este arquivo deve estar na mesma pasta dos dois projetos (PersonCRUD e front_pessoa_crud)
version: "2"
services:
  postgres:
    image: postgres:latest    
    container_name: postgres_bd
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:         
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_DB=cadastro_pessoa
    restart: unless-stopped
    networks:
      - backend
# BACK*****************************************
  app-server:
    build:
      context: PersonCRUD # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    expose:
      - 4060
    ports:
      - 4060:4060
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cadastro_pessoa
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
# FRONt*********************************************
  app-client:
    build:
      context: front_pessoa_crud # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - "9090:80" # Map the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  

volumes:
  postgres-data:

networks:
  backend:
  frontend:

